//
// Created by Lenovo on 17/03/2023.
//

#ifndef SISTEMA_HUESPEDES_MARIA_VALERIA_EVALUACION_H
#define SISTEMA_HUESPEDES_MARIA_VALERIA_EVALUACION_H


class Evaluacion {

};


#endif //SISTEMA_HUESPEDES_MARIA_VALERIA_EVALUACION_H
