//
// Created by Lenovo on 17/03/2023.
//

#ifndef SISTEMA_HUESPEDES_MARIA_VALERIA_HOGAR_H
#define SISTEMA_HUESPEDES_MARIA_VALERIA_HOGAR_H


class hogar {

};


#endif //SISTEMA_HUESPEDES_MARIA_VALERIA_HOGAR_H
