//
// Created by Lenovo on 17/03/2023.
//

#ifndef SISTEMA_HUESPEDES_MARIA_VALERIA_PROPIETARIO_H
#define SISTEMA_HUESPEDES_MARIA_VALERIA_PROPIETARIO_H


class Propietario {

};


#endif //SISTEMA_HUESPEDES_MARIA_VALERIA_PROPIETARIO_H
